Add DNS admin service account in anticipation of using a wildcard cert for Istio ingress gateway

diff --git a/scripts/credentials-google b/scripts/credentials-google
--- a/scripts/credentials-google
+++ b/scripts/credentials-google
@@ -6,15 +6,15 @@ set -xeuo pipefail
 source "environments/admin/credentials.env"
 
 set +e
-if ! gcloud projects list | grep --quiet "${GOOGLE_ENVIRONMENT}"; then
-  echo "ERROR: Project for ${GOOGLE_ENVIRONMENT} not found"
+if ! gcloud projects list | grep --quiet "${ENVIRONMENT}"; then
+  echo "ERROR: Project for ${ENVIRONMENT} not found"
   exit 1
 fi
 set -e
 
 GOOGLE_PROJECT_ID=$(
   gcloud projects list \
-    | grep "${GOOGLE_ENVIRONMENT}" \
+    | grep "${ENVIRONMENT}" \
     | awk '{ print $2 }'
 )
 
